---
author: Sebastian Höffner
title: Gaze tracking using common webcams
institute: Institute of Cognitive Science
workgroup: Biologically Oriented Computer Vision
city: Osnabrück
firstSupervisor: Prof. Dr. Gunther Heidemann
secondSupervisor: Julius Schöning, M. Sc.
date: February 2, 2018
header-includes:
    - \def\gaze{Gaze}
    - \usepackage{siunitx}
panflute-filters:
    - todo
    - glossary
panflute-path: bin/panflute
...
