---
author: Sebastian Höffner
title: Gaze Tracking Using Common Webcams
institute: Institute of Cognitive Science
workgroup: Biologically oriented Computer Vision
city: Osnabrück
firstSupervisor: Prof.\ Dr.\ Gunther Heidemann
secondSupervisor: Julius Schöning, M.\ Sc.
date: February 1, 2018
abstract: src/abstract.tex
acknowledgements: src/acknowledgements.tex
header-includes:
    - \def\Gaze{\textsf{Gaze}}
    - \newcommand{\exchangerateUSDEUR}{0.804804}
    - \newcommand{\eur}[1]{\SI{#1}[{EUR\,}]{}}
    - '\newcommand{\usd}[1]{\eur{\xinttheiexpr\xintexpr \exchangerateUSDEUR * #1 \relax\relax}}'
header-files:
    - assets/math.tex
panflute-filters:
    - fileinput
    - todo
    - pandoc-img-glob
    - pandoc-source-exec
    - stripcomments
    - pandoc-custom-refnos
    - glossary
panflute-path: bin/panflute
fignos-cleveref: true
fignos-capitalize: true
fignos-plus-name:
    - Figure
    - Figures
...
