---
author: Sebastian Höffner
title: Gaze
subtitle: Gaze tracking using common webcams
date:
header-includes:
    - \usepackage{siunitx}
    - \usepackage[]{todonotes}
    - \def\gaze{\texttt{gaze}}
panflute-filters:
    - todo
panflute-path: bin/panflute
...
